# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Tuan Phan
description: "Hello, my name is Tuan Phan, and I am an Applied Mathematician as well as a Data Scientist. My portfolio showcases a selection of recent projects, each highlighting significant business impact. I invite you to explore my GitHub and LinkedIn profiles or download my resume using the links provided below."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Idaho, US"
resume_url: /docs/TuanPhan_Resume.pdf
avatar_image: /img/tphan86_image_squared.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/tuan-phan-97b99271/" # Add your linkedln handle
github: "https://github.com/tphan86"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

